### ISSUE TITLE
Carousel not working in Safari

### ISSUE THREAD

**Issue by MatheusBordin** [latte-carousel/latte-carousel#5]
**Describe the bug**
Carousel didn't mount in Safari / IOS.

**To Reproduce**
Create latte-carousel instance in Safari.

**Expected behavior**
Carousel works fine in IOS.

**Smartphone (please complete the following information):**

-   Device: IPhone 8 / IPad
-   OS: IOS.
-   Browser: Chrome / Safari.

**Comment by felipe-fg** [comment]
Old Safari versions required a vendor prefix for transform property.

Fixed in version 1.5.3.
