### ISSUE TITLE
Auto-scroll timer reset

### ISSUE THREAD

**Issue by duckyb** [latte-carousel/latte-carousel#7]
**Is your feature request related to a problem? Please describe.**
If automatic scrolling and interactions are enabled, it can happen that the user clicks on a dot or an arrow and the slideshow moves to the selected slide and then immedeately goes to the next slide.

**Describe the solution you'd like**
Reset the auto-scrolling timer every time the user interacts with the carousel.

**Describe alternatives you've considered**
Giving an option for this would also be ok

![img](https://i.imgur.com/Ia4C1DA.gif)

**Comment by felipe-fg** [comment]
Hello, @duckyb.

Thank you for pointing this out.

It will be fixed on the next release.
